In [75]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv('../Data/Churn_Modelling.xls')

In [48]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [49]:
df.shape

(10000, 14)

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [51]:
df.duplicated().sum()

np.int64(0)

In [52]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [53]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [54]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [55]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace=True)

In [56]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [57]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)

In [58]:
X = df.drop(columns=['Exited'])
y = df['Exited']

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [60]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,False,False,False

In [61]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [62]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]], shape=(8000, 11))

In [63]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input

### 11 Inputs
###    ↓
### Hidden Layer (3 neurons)
###   ↓
### Output Layer (1 neuron)

In [67]:
model = Sequential()

model.add(Input(shape=(11,)))
model.add(Dense(3, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [68]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [69]:
model.compile(loss='binary_crossentropy', optimizer='Adam')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [70]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5497
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - loss: 0.4935
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - loss: 0.4707
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - loss: 0.4586
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - loss: 0.4502
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - loss: 0.4438
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step - loss: 0.4388
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - loss: 0.4348
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - loss: 0.4314
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - loss: 0.4285

In [71]:
model.layers[0].get_weights()

[array([[-0.12899324,  0.25450987,  0.08597593],
        [-1.2068359 , -1.9746367 , -0.8175778 ],
        [-0.13734607,  0.09118741,  0.07032836],
        [ 0.07082521, -0.31156954, -0.22986147],
        [ 0.2696417 , -0.29436758,  1.6603312 ],
        [-0.33998698,  0.16396809,  0.31867552],
        [ 1.200461  ,  0.45304358,  0.5948784 ],
        [-0.23625922, -0.12911685,  0.23819132],
        [-1.1305408 , -0.39841864, -0.24104685],
        [ 0.10570438,  0.20632304, -0.31787542],
        [ 0.75792927,  0.5646143 ,  0.04404299]], dtype=float32),
 array([0.47371486, 0.2495386 , 0.47481114], dtype=float32)]

In [73]:
y_log = model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step

In [74]:
y_log

array([[0.11335764],
       [0.14208181],
       [0.13459104],
       ...,
       [0.06306743],
       [0.13421871],
       [0.3874673 ]], shape=(2000, 1), dtype=float32)

In [77]:
y_pred = np.where(y_log>0.5,1,0)

In [78]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], shape=(2000, 1))

In [79]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7925